"""Contact-submission retention (spec 002 FR-024b).

The contact form tells every visitor, at the point of collection, that their message
is kept for 90 days and then deleted. Until this task existed, nothing deleted
anything — the notice was a promise with no mechanism, and the only ``DELETE``
against ``contact_submissions`` anywhere in the repository was a test's own cleanup
fixture.

Three decisions worth stating, because each could reasonably have gone the other
way:

**Wall-clock time, not the pinned reference date.** Everything generated by feature
001 is dated against ``REFERENCE_DATE``, and using ``reference_datetime()`` here
would have been the consistent-looking choice. It would also be wrong: submissions
are *runtime* data written by real visitors at real times — that is why they are
excluded from the dataset fingerprint — so a retention window measured against a
frozen date would either delete everything or nothing depending on where that date
sat relative to today.

**The owner role, not the application role.** Migration 0003 grants ``eaios_app``
only ``SELECT, INSERT`` on this table, deliberately: the public site writes and never
reads, and nothing in the request path should be able to delete a visitor's record.
Retention is a data-lifecycle operation, not an application operation, so it runs as
the owner rather than widening the grant. The owner bypasses RLS, so the tenant
predicate is written explicitly below — an owner-role query with no ``company_id``
filter would be a cross-tenant delete.

**Deletes by age only, and reports the count.** No batching, no soft delete. The
volume is a public contact form's, and a row that is 91 days old must be gone rather
than flagged; FR-024b says deleted.

**Audited, including when it deletes nothing.** Constitution Principle X requires an
audit record for every consequential operation, and erasing a member of the public's
personal data is one — it is irreversible, and "when was this person's record
deleted, and by what?" is the question the audit trail exists to answer. The first
version of this module wrote a log line and no audit row. A run that deletes zero
rows still writes its entry, because *the job ran and found nothing* and *the job
never ran* are precisely the two states the record has to distinguish.
"""

from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import delete
from sqlalchemy.engine import Engine

from eaios_core.db import create_owner_engine, session_scope
from eaios_core.logging import get_logger
from eaios_core.models import AuditLog, ContactSubmission

from ..celery_app import celery_app
from .base import TenantTask

logger = get_logger(__name__)

__all__ = [
    "RETENTION_ACTION",
    "RETENTION_DAYS",
    "purge_contact_submissions",
    "purge_expired_submissions",
]

#: The action name the audit entry carries. Named as a constant so the test asserts
#: against the same string the task writes rather than a copy of it.
RETENTION_ACTION = "retention.purge"

#: FR-024b, and the number stated to the visitor in `ContactForm.tsx`. Changing it
#: here without changing the notice would make the site lie to the people it
#: collects data from — `tests/integration/test_retention.py` binds the two.
RETENTION_DAYS = 90


def purge_contact_submissions(
    company_id: str,
    *,
    engine: Engine | None = None,
    now: dt.datetime | None = None,
) -> int:
    """Delete submissions older than the retention window. Returns the row count.

    ``now`` is injectable so a test can place rows either side of the boundary
    without waiting 90 days; it defaults to the wall clock.
    """
    moment = now or dt.datetime.now(tz=dt.UTC)
    cutoff = moment - dt.timedelta(days=RETENTION_DAYS)
    engine = engine or create_owner_engine()

    with session_scope(engine) as session:
        result = session.execute(
            delete(ContactSubmission).where(
                # Explicit tenant predicate: the owner role bypasses RLS, so the
                # policy that normally makes this impossible to get wrong is not
                # in force here.
                ContactSubmission.company_id == company_id,
                ContactSubmission.submitted_at < cutoff,
            )
        )
        deleted = int(result.rowcount or 0)

        # Written in the same transaction as the delete. Separating them would allow
        # rows to disappear with no record of it — the one outcome an audit trail
        # must not permit.
        session.add(
            AuditLog(
                id=uuid.uuid4(),
                company_id=company_id,
                actor_user_id=None,
                actor_type="SYSTEM",
                action=RETENTION_ACTION,
                resource_type="contact_submissions",
                # The window that was applied, not any row that fell inside it.
                # FR-024c forbids carrying a sender, an address, or a message into
                # a table other people read.
                resource_id=f"submitted_at<{cutoff.isoformat()}",
                decision="ALLOW",
                reason=f"retention window of {RETENTION_DAYS} days applied; {deleted} deleted",
                sources=[],
                created_at=moment,
            )
        )

    # The count only — never a sender, an address, or a subject line (FR-024c).
    logger.info(
        "retention.purged",
        table="contact_submissions",
        deleted=deleted,
        cutoff=cutoff.isoformat(),
        retention_days=RETENTION_DAYS,
    )
    return deleted


# Celery ships no type stubs, so its decorator erases the signature.
@celery_app.task(  # type: ignore[misc]
    base=TenantTask, name="eaios.retention.purge_expired_submissions"
)
def purge_expired_submissions(*, company_slug: str) -> int:
    """Scheduled entry point. ``company_slug`` is required by `TenantTask`."""
    from eaios_core.ids import derive

    company_id = derive("company", company_slug, company_slug)
    return purge_contact_submissions(str(company_id))
