"""Authentication entities (spec 003, data-model.md §1).

Two tables, both tenant-owned. Neither is generated by the seed — they are runtime
state, written after the dataset exists — so neither contributes rows to the
fingerprint. That is the property FR-002a depends on and SC-014 measures.

**The class is `UserSession`, the table is `sessions`.** Naming the class `Session`
would put it one import away from colliding with `sqlalchemy.orm.Session` in every
module that touches both — which is every module that reads one. A shadowed name in
the layer that decides who is signed in is not a place to be clever.
"""

from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import CheckConstraint, ForeignKey, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TenantMixin, TimestampMixin, tenant_index, uuid_pk

__all__ = ["UserCredential", "UserSession"]


class UserCredential(Base, TenantMixin, TimestampMixin):
    """The stored, non-recoverable verifier for one user's sign-in (FR-002).

    Its own table rather than ``users.password_hash``, for two reasons that pull the
    same way. The credential has a different lifecycle from the user — the generator
    writes users, a separate post-seed command writes credentials (FR-002a), and a
    reset clears both independently. And a password hash is unambiguously a
    company-owned artifact, so it belongs behind RLS with everything else Principle I
    covers, not in a global table made convenient by the sign-in lookup.

    ``users.password_hash`` still exists and is never used. Dropping it is the tidier
    outcome and is rejected: the generator writes ``"password_hash": None`` into every
    user row, that key is part of the hashed row, and removing it would move both
    committed fingerprints — which SC-014 forbids. The trap is closed by
    ``tests/security/test_password_hash_column_unused.py`` rather than by this comment.

    Never returned by an endpoint, never logged, never audited (FR-018).
    """

    __tablename__ = "user_credentials"
    __table_args__ = (UniqueConstraint("user_id"),)

    id: Mapped[uuid.UUID] = uuid_pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    #: Argon2id encoded string — algorithm, parameters, and a per-hash random salt all
    #: travel with the value, so `verify` reads them from what was stored rather than
    #: from configuration that could have drifted since.
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)


class UserSession(Base, TenantMixin, TimestampMixin):
    """A time-bounded grant of access to one user (FR-005, FR-007).

    Server-side state is what makes signing out real. A self-contained credential
    cannot be withdrawn: without a row to mark ended, "sign out" would delete the
    client's copy and leave the credential valid until expiry, and FR-007 would be
    false as written. The cost is small because the lookup already had to happen —
    FR-004 requires active status and tenant membership to be read from current records
    on every request, so session validity joins a query that runs regardless.

    **Two expiry columns, not one.** ``absolute_expires_at`` is set at sign-in and never
    moves; ``last_seen_at`` advances with use. A single "expires at" pushed forward on
    activity silently discards the absolute cap, which is the only bound that limits how
    long a stolen credential stays useful — the precise failure the second bound exists
    to prevent.
    """

    __tablename__ = "sessions"
    __table_args__ = (
        CheckConstraint("absolute_expires_at > issued_at", name="expiry_after_issue"),
        CheckConstraint(
            "ended_reason IN ('SIGN_OUT','IDLE','ABSOLUTE')", name="ended_reason_values"
        ),
        # Both columns say the session ended, or neither does. A row with one but not
        # the other is a state no reader should have to interpret, and the database is
        # a better place to refuse it than every query that reads it.
        CheckConstraint(
            "(ended_at IS NULL) = (ended_reason IS NULL)", name="ended_consistently"
        ),
        tenant_index("sessions", "user_id", "ended_at"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    issued_at: Mapped[dt.datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    absolute_expires_at: Mapped[dt.datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False
    )
    last_seen_at: Mapped[dt.datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)

    ended_at: Mapped[dt.datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    #: SIGN_OUT | IDLE | ABSOLUTE. Recorded rather than inferred, so the audit entry and
    #: the interface can both say *why* a session ended — "your session expired" and
    #: "you signed out" are different sentences and the user knows which they did.
    ended_reason: Mapped[str | None] = mapped_column(String(16), nullable=True)
