"""Public-site entities — the one table the public website writes (spec 002).

Everything else the site displays was generated by feature 001 and is read
without modification. This is runtime data rather than generated data, which is
why it is excluded from the dataset fingerprint (research R8) — a visitor
submitting a message must not change what `verify` reports.
"""

from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import CheckConstraint, Index, String, Text
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TenantMixin, TimestampMixin, uuid_pk

__all__ = ["ContactSubmission"]


class ContactSubmission(Base, TenantMixin, TimestampMixin):
    """A message left by an anonymous visitor (spec 002 FR-019 – FR-024c).

    Written by the public site, never read by it (FR-023b). There is no public
    read route at all — the absence is structural rather than a filter that could
    later be relaxed.

    `company_id` comes from `TenantMixin` and is fixed server-side to NileTech
    (FR-009a); it is never taken from the request. Because the mixin makes it
    non-nullable, feature 001's structural audit accepts this as a tenant-owned
    table and the RLS policy derived from `tenant_tables()` applies to it
    automatically.
    """

    __tablename__ = "contact_submissions"
    __table_args__ = (
        # Bounds mirror FR-019 exactly. They live here as well as in the request
        # model because FR-020 makes the server the control, and the database
        # constraint is the last one standing if a future caller bypasses the API
        # layer.
        CheckConstraint("char_length(sender_name) BETWEEN 1 AND 120", name="sender_name_length"),
        CheckConstraint("char_length(sender_email) BETWEEN 3 AND 254", name="sender_email_length"),
        CheckConstraint("char_length(subject) BETWEEN 1 AND 150", name="subject_length"),
        CheckConstraint("char_length(message) BETWEEN 1 AND 4000", name="message_length"),
        # Duplicate suppression looks up recent submissions by hash within a
        # window (FR-022). Deliberately an index and not a unique constraint:
        # permanent uniqueness would silently reject a genuine later enquiry that
        # happened to repeat a short message.
        Index(
            "ix_contact_submissions_dedupe",
            "company_id",
            "content_hash",
            "submitted_at",
        ),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    sender_name: Mapped[str] = mapped_column(String(120), nullable=False)
    sender_email: Mapped[str] = mapped_column(String(254), nullable=False)
    subject: Mapped[str] = mapped_column(String(150), nullable=False)
    #: Stored verbatim and never interpreted as markup (FR-024).
    message: Mapped[str] = mapped_column(Text, nullable=False)
    #: SHA-256 over the normalized fields — the duplicate-suppression key.
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    #: Wall clock. This is runtime data; the pinned reference date does not apply.
    submitted_at: Mapped[dt.datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
