"""Render `docs/personas.md` and `docs/dataset.md` from the generated dataset.

`docs/README.md` claimed these files were "generated from the live database ... so
they cannot drift into describing records that do not exist". No generator existed.
They drifted: eight of the ten personas named the wrong person, and both files were
stamped with a stale generator version and fingerprint. Nobody noticed for several
convergence passes, because the claim read like a guarantee.

Rendering happens **from the in-process dataset, not from a live database**, which is
a deliberate departure from the original wording. The generator is deterministic
(FR-011), so the two agree by construction — and a docs-freshness check that needs a
running stack is a check that skips itself whenever the stack is down. This project
has already shipped several tests that quietly did exactly that.

Both documents are rendered whole, prose included, so there is no hand-maintained
region that can fall out of step with the generated tables.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from eaios_core.constants import COMPANY_NAMES, GENERATOR_VERSION

from .config import SeedConfig
from .dataset import Dataset
from .generators.markers import markers_for
from .generators.organization import OrgContext
from .manifest import compute_digests
from .pipeline import build_complete_dataset

__all__ = ["DOCUMENTS", "render_all", "render_dataset", "render_personas", "write_all"]

#: Repo-relative output paths.
DOCUMENTS = ("docs/personas.md", "docs/dataset.md")

#: The documentation describes the dataset a demo runs on, which is the CLI default.
DOC_PROFILE = "full"

_PERSONA_PURPOSE = {
    "employee.engineering": "Reads the general leave policy; reads **their own** leave balance",
    "manager.engineering": (
        "Reads **direct reports'** leave; heads Engineering with reports of its own"
    ),
    "employee.sales": (
        "The out-of-scope target — a different department the Engineering manager "
        "must **not** reach"
    ),
    "hr.generalist": "Company-wide HR access, including the payroll register",
    "finance.analyst": "Financial reads",
    "legal.counsel": "Holds an explicit resource ACL on the two comparable contracts",
    "auditor.readonly": "Reads audit evidence and nothing else",
    "admin.company": "User and role administration",
    "comms.sender": "Holds `communications:send`, so the approval gate has something to gate",
    "employee.delta": "The other tenant — origin and target of the cross-tenant probe",
}


def _index(rows: list[dict[str, Any]], key: str = "id") -> dict[Any, dict[str, Any]]:
    return {row[key]: row for row in rows}


def _primary_role(dataset: Dataset) -> dict[Any, str]:
    """user id → primary role name. `is_primary` is on the join row (FR-025a)."""
    roles = _index(dataset.rows["roles"])
    return {
        link["user_id"]: roles[link["role_id"]]["name"]
        for link in dataset.rows["user_roles"]
        if link.get("is_primary")
    }


def render_personas(dataset: Dataset, config: SeedConfig) -> str:
    users = _index(dataset.rows["users"])
    departments = _index(dataset.rows["departments"])
    companies = _index(dataset.rows["companies"])
    primary = _primary_role(dataset)

    reports: dict[Any, int] = {}
    for user in dataset.rows["users"]:
        if user.get("manager_id"):
            reports[user["manager_id"]] = reports.get(user["manager_id"], 0) + 1

    personas = sorted(
        (u for u in dataset.rows["users"] if u.get("persona_key")),
        key=lambda u: (companies[u["company_id"]]["slug"] != "niletech", u["persona_key"]),
    )

    lines = [
        "# Persona reference",
        "",
        "Satisfies **FR-025b**. These ten users have stable identifiers and are referenced by",
        "name in acceptance tests, the evaluation set, and the defense demo script. Their",
        "identity does not change between seed runs — that stability is the point (FR-025c),",
        "and `tests/security/test_scenario_readiness.py` pins the mapping below so a silent",
        "reassignment fails there rather than surfacing as a fingerprint mismatch.",
        "",
        "<!-- GENERATED by `make docs` — edit scripts/seed/src/eaios_seed/docgen.py, not this file. -->",
        "",
        f"Generated at generator version `{GENERATOR_VERSION}`, profile `{config.profile}`,",
        f"seed `{config.seed}`, reference date `{config.reference_date.isoformat()}`.",
        "",
        "| Persona key | Company | Department | Primary role | Country | Name | Sign-in address | Reports to | Direct reports |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    for user in personas:
        manager = users.get(user.get("manager_id")) if user.get("manager_id") else None
        lines.append(
            f"| `{user['persona_key']}` "
            f"| {companies[user['company_id']]['slug']} "
            f"| {departments[user['department_id']]['name']} "
            f"| {primary.get(user['id'], '—')} "
            f"| {user['country']} "
            f"| {user['full_name']} "
            f"| `{user['email']}` "
            f"| {manager['full_name'] if manager else '— (top level)'} "
            f"| {reports.get(user['id'], 0)} |"
        )

    lines += [
        "",
        "## What each persona is for",
        "",
        "Each maps to one of the blueprint's eight access-control scenarios. This dataset",
        "guarantees the records exist to express them, and feature 003 enforces them — the",
        "manager/direct-report and salary-denial scenarios are proved against these exact",
        "people by `tests/security/test_manager_scope.py` and",
        "`tests/security/test_authorize_before_read.py`.",
        "",
        "| Persona | Scenario it serves |",
        "|---|---|",
    ]
    for user in personas:
        purpose = _PERSONA_PURPOSE.get(user["persona_key"], "—")
        lines.append(f"| `{user['persona_key']}` | {purpose} |")

    lines += [
        "",
        "## Using them",
        "",
        "Look a persona up by its key, never by name — names are generated and would change",
        "if the seed did:",
        "",
        "```sql",
        "SELECT * FROM users WHERE persona_key = 'manager.engineering';",
        "```",
        "",
        "## Signing in",
        "",
        "Every active user above can sign in at <http://localhost:3000/portal> once",
        "credentials have been provisioned:",
        "",
        "```bash",
        "make up && make seed && make credentials",
        "```",
        "",
        "`make credentials` is a separate step from seeding, and stays separate on purpose",
        "(spec 003 FR-002a). The generator leaves `users.password_hash` unset — it is never",
        "written, by anything — and credentials live in their own `user_credentials` table",
        "written after generation. That ordering is what keeps the dataset fingerprint",
        "stable: it is computed from the in-process generated rows, so a credential written",
        "afterwards cannot move it.",
        "",
        "The command prints the password it uses and refuses to run outside",
        "`ENVIRONMENT=local`. It is a deliberately weak, shared placeholder for a",
        "demonstration dataset in which no real person is behind any account.",
        "",
        "**Re-run it after `make reset`**, which clears credentials along with every other",
        "runtime table.",
        "",
    ]
    return "\n".join(lines)


def render_dataset(dataset: Dataset, ctx: OrgContext, config: SeedConfig) -> str:
    counts = dict(dataset.counts_by_company(ctx.company_ids))
    _families, _files, fingerprint = compute_digests(dataset, ctx.company_ids)

    companies = _index(dataset.rows["companies"])
    headcount: dict[str, int] = {}
    for user in dataset.rows["users"]:
        slug = companies[user["company_id"]]["slug"]
        headcount[slug] = headcount.get(slug, 0) + 1

    def offices_of(slug: str) -> str:
        rows = [
            office
            for office in dataset.rows["offices"]
            if companies[office["company_id"]]["slug"] == slug
        ]
        rows.sort(key=lambda office: (not office["is_headquarters"], office["city"]))
        return ", ".join(
            f"{office['city']} (HQ)" if office["is_headquarters"] else office["city"]
            for office in rows
        )

    def departments_of(slug: str) -> str:
        return ", ".join(
            sorted(
                department["name"]
                for department in dataset.rows["departments"]
                if companies[department["company_id"]]["slug"] == slug
            )
        )

    lines = [
        "# The synthetic dataset",
        "",
        "Two isolated companies generated deterministically from one seed. Nothing here is",
        "real: no real person, no real company, no real contract.",
        "",
        "<!-- GENERATED by `make docs` — edit scripts/seed/src/eaios_seed/docgen.py, not this file. -->",
        "",
        "| | |",
        "|---|---|",
        f"| Seed | `{config.seed}` |",
        f"| Reference date | `{config.reference_date.isoformat()}` |",
        f"| Generator version | `{GENERATOR_VERSION}` |",
        f"| Profile | `{config.profile}` |",
        f"| Fingerprint | `{fingerprint}` |",
        "",
        "## The two tenants",
        "",
        "| Company | Employees |",
        "|---|---|",
    ]
    for slug in ("niletech", "delta-retail"):
        lines.append(f"| {slug} | {headcount.get(slug, 0)} |")

    lines += [
        "",
        f"**{COMPANY_NAMES['niletech']}** — software and business automation. "
        f"{offices_of('niletech')}.",
        f"Departments: {departments_of('niletech')}.",
        "",
        f"**{COMPANY_NAMES['delta-retail']}** — wholesale and retail distribution. "
        f"{offices_of('delta-retail')}.",
        f"Departments: {departments_of('delta-retail')}.",
        "",
        "## Delta Retail's intentional absences",
        "",
        "Satisfies **FR-022**. Delta Retail has **no Engineering department and no Legal",
        "department**. This is deliberate, not a generation gap:",
        "",
        "- It makes the tenants structurally different, so a query that accidentally assumes",
        "  one shape breaks loudly instead of quietly returning the wrong tenant's data.",
        "- It exercises the document-ownership fallback (FR-031a): contracts in a company",
        "  without a Legal department fall to the head of Executive Management.",
        "- A retail distributor plausibly outsources both functions.",
        "",
        "`tests/integration/test_org_hierarchy.py` asserts the absence, so it cannot be",
        '"fixed" by accident.',
        "",
        "## What this dataset deliberately does not contain",
        "",
        "**A synthetic code repository.** The blueprint lists one (authentication, leave,",
        "reporting, notification modules) for the code-aware RAG demo. It is deferred to the",
        "ingestion feature as decision D4: nothing in this feature can consume it, and its",
        "chunking strategy should be designed alongside the retriever that has to use it —",
        "not months earlier, in isolation.",
        "",
        "**Document embeddings.** Qdrant collections are provisioned with a `company_id`",
        "payload index and left empty (decision D2), so the filter path exists before any",
        "content does.",
        "",
        "## Document attributes and the country exemption",
        "",
        "FR-010 requires sensitive resources to carry owner, department, country, and",
        "classification, so the authorization feature has attributes to filter on.",
        "",
        "**Department is never null.** It follows the document's owner, which is the same rule",
        "FR-031a already states for ownership — so the two cannot disagree. This matters most",
        "for Delta Retail: it has no Legal department, so its contracts fall to the head of",
        "Executive Management, and they are attributed to that department rather than to none.",
        "",
        '**Country is null for company-wide documents, and that is the correct value** — it',
        'means "not restricted by country", not "unknown". Three document types are',
        "company-wide by nature:",
        "",
        "| Type | Why it has no country |",
        "|---|---|",
        "| `POLICY` | Policies apply to all personnel across all offices; the leave policy "
        "states per-country entitlements *inside* its text rather than being scoped to one |",
        "| `PUBLIC` | The public page describes the whole company |",
        "| `REPORT` | The RESTRICTED payroll register spans both countries the company "
        "operates in |",
        "",
        "Every other type must carry a country, and",
        "`tests/integration/test_document_ownership.py` asserts both halves — including that",
        "this exemption list has not quietly grown to cover everything.",
        "",
        "## Cross-tenant markers",
        "",
        "Each tenant's documents carry distinctive phrases that appear nowhere in the other's",
        "content, so a leak is unambiguous rather than a judgement call:",
        "",
        "| Company | Marker |",
        "|---|---|",
        f"| NileTech | `{markers_for('niletech')[0]}` |",
        f"| Delta Retail | `{markers_for('delta-retail')[0]}` |",
        "",
        "## Realized counts",
        "",
        "| Family | Rows |",
        "|---|---|",
    ]
    for family in sorted(counts):
        lines.append(f"| `{family}` | {counts[family]:,} |")

    lines += [
        "",
        "## Regenerating",
        "",
        "```bash",
        "make reset",
        "```",
        "",
        "Destroys everything and regenerates. The fingerprint above must come back",
        "identical — see [determinism.md](determinism.md).",
        "",
        "This document and [personas.md](personas.md) are rendered by `make docs`;",
        "`tests/unit/test_docs_freshness.py` fails when either drifts from the generator.",
        "",
    ]
    return "\n".join(lines)


def render_all() -> dict[str, str]:
    """Repo-relative path → rendered content, for both documents."""
    config = SeedConfig.build(profile=DOC_PROFILE)  # type: ignore[arg-type]
    dataset, ctx = build_complete_dataset(config)
    return {
        "docs/personas.md": render_personas(dataset, config),
        "docs/dataset.md": render_dataset(dataset, ctx, config),
    }


def write_all(root: Path) -> list[Path]:
    written: list[Path] = []
    for relative, content in render_all().items():
        path = root / relative
        # LF and UTF-8 without a BOM, matching every other generated artifact
        # (FR-012a). A CRLF here would make the freshness check fail on Windows
        # for a reason that has nothing to do with the dataset.
        path.write_text(content, encoding="utf-8", newline="\n")
        written.append(path)
    return written
