"""Deterministic identifier derivation (research R1).

Identifiers are UUIDv5 values computed from a stable natural key, not generated by
the database and not drawn from a random source. Three consequences make this the
right choice for a reproducible dataset:

* Same seed + same natural key produces the same UUID on every machine, in any
  language, with no coordination.
* IDs are computed *before* insertion, so the generator can build the whole object
  graph in memory and insert in any order — or in parallel — without changing a
  single identifier.
* Natural keys make failures debuggable: a broken test can name the exact entity.

The rejected alternatives are recorded in research.md; the short version is that
sequential integers tie identity to insertion order, and seeded UUIDv4 ties it to
call order. Both turn an ordinary refactor into a dataset-changing event.
"""

from __future__ import annotations

import uuid
from typing import Final

from .constants import ROOT_SEED

__all__ = ["NAMESPACE_ROOT", "dataset_namespace", "derive", "derive_global"]

#: Fixed project root namespace. Changing this moves every identifier in the
#: dataset; `tests/unit/test_ids.py::TestFrozenFixtures` exists to make that loud.
NAMESPACE_ROOT: Final[uuid.UUID] = uuid.uuid5(uuid.NAMESPACE_DNS, "eaios.local")

# Distinct prefixes keep the tenant-scoped and global namespaces from ever colliding,
# even if a caller passed "global" as a company slug.
_TENANT_URN: Final[str] = "{entity}:{company}:{key}"
_GLOBAL_URN: Final[str] = "global!{entity}:{key}"


def dataset_namespace(seed: str = ROOT_SEED) -> uuid.UUID:
    """The namespace for one dataset. A different seed is a different dataset."""
    return uuid.uuid5(NAMESPACE_ROOT, f"seed:{seed}")


def derive(entity: str, company_slug: str, natural_key: str, seed: str = ROOT_SEED) -> uuid.UUID:
    """Derive the identifier of a tenant-owned entity.

    Args:
        entity: Entity type, e.g. ``"user"`` or ``"order"``.
        company_slug: Owning tenant, e.g. ``"niletech"``.
        natural_key: Stable key unique within (entity, company), e.g. ``"employee-0042"``.
        seed: Root seed; defaults to the committed value.
    """
    urn = _TENANT_URN.format(entity=entity, company=company_slug, key=natural_key)
    return uuid.uuid5(dataset_namespace(seed), urn)


def derive_global(entity: str, natural_key: str, seed: str = ROOT_SEED) -> uuid.UUID:
    """Derive the identifier of a global (non-tenant-owned) entity.

    Only the four entities on the allowlist in :mod:`eaios_core.tenancy` may use this.
    """
    urn = _GLOBAL_URN.format(entity=entity, key=natural_key)
    return uuid.uuid5(dataset_namespace(seed), urn)
