"""Contact submissions from the public website.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-02

The only table the public site writes (spec 002 FR-023). Everything else the site
displays was generated by feature 001 and is read unmodified.

Two properties matter more than the columns:

* It is **tenant-owned**, so it carries a non-nullable ``company_id`` and gets the
  same ``tenant_isolation`` policy as every other tenant table. Migration 0002
  derived its table list from ``tenant_tables()``, which reads the metadata — but
  0002 has already run, so the policy is applied here explicitly rather than being
  inherited. `tests/security/test_rls.py` and the schema audit both walk
  ``tenant_tables()`` and will now include this table, so a missing policy fails
  there rather than going unnoticed.
* It holds **runtime** data, not generated data. It is therefore excluded from the
  dataset fingerprint, added to the reset truncation set, and counted by the seed's
  emptiness pre-flight (research R8) — three changes in `scripts/seed` without which
  feature 001's guarantees would quietly stop holding.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.dialects.postgresql import UUID as PgUUID

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "contact_submissions"
_POLICY = "tenant_isolation"
_APP_ROLE = "eaios_app"


def upgrade() -> None:
    op.create_table(
        _TABLE,
        sa.Column("id", PgUUID(as_uuid=True), primary_key=True),
        sa.Column(
            "company_id",
            PgUUID(as_uuid=True),
            sa.ForeignKey("companies.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("sender_name", sa.String(120), nullable=False),
        sa.Column("sender_email", sa.String(254), nullable=False),
        sa.Column("subject", sa.String(150), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("submitted_at", TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "char_length(sender_name) BETWEEN 1 AND 120",
            name="ck_contact_submissions_sender_name_length",
        ),
        sa.CheckConstraint(
            "char_length(sender_email) BETWEEN 3 AND 254",
            name="ck_contact_submissions_sender_email_length",
        ),
        sa.CheckConstraint(
            "char_length(subject) BETWEEN 1 AND 150",
            name="ck_contact_submissions_subject_length",
        ),
        sa.CheckConstraint(
            "char_length(message) BETWEEN 1 AND 4000",
            name="ck_contact_submissions_message_length",
        ),
    )

    # TenantMixin indexes company_id on every other tenant table; matched here so
    # feature 001's `test_tenant_columns` finds the same shape it expects.
    op.create_index("ix_contact_submissions_company_id", _TABLE, ["company_id"])
    op.create_index(
        "ix_contact_submissions_dedupe",
        _TABLE,
        ["company_id", "content_hash", "submitted_at"],
    )

    op.execute(f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY {_POLICY} ON {_TABLE}
        USING (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
        """
    )
    # INSERT and SELECT only. The public surface writes and never reads (FR-023b),
    # and nothing in this feature updates or deletes a submission.
    op.execute(f"GRANT SELECT, INSERT ON {_TABLE} TO {_APP_ROLE}")


def downgrade() -> None:
    op.execute(f"REVOKE SELECT, INSERT ON {_TABLE} FROM {_APP_ROLE}")
    op.execute(f"DROP POLICY IF EXISTS {_POLICY} ON {_TABLE}")
    op.drop_index("ix_contact_submissions_dedupe", table_name=_TABLE)
    op.drop_index("ix_contact_submissions_company_id", table_name=_TABLE)
    op.drop_table(_TABLE)
