"""The committed documentation matches the dataset it describes (spec FR-048).

`docs/README.md` used to assert that `personas.md` and `dataset.md` were "generated
from the live database ... so they cannot drift into describing records that do not
exist". No generator existed, so nothing produced or checked them, and both files
carried a stale generator version and a stale fingerprint for two releases.

The assurance was worse than the staleness. It was read as a guarantee during four
convergence passes, and during the fifth it caused a *false* alarm: the persona
table was compared against a smoke-seeded database and eight names looked wrong,
when in fact the document describes the full profile and was correct. A claim with
nothing behind it misleads in both directions.

These run as unit tests, without a database, because the generator is deterministic
(FR-011) and a freshness check that needs a running stack would skip itself exactly
when nobody is watching.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from eaios_core.constants import GENERATOR_VERSION
from eaios_seed.docgen import DOCUMENTS, render_all

pytestmark = pytest.mark.unit

REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture(scope="module")
def rendered() -> dict[str, str]:
    return render_all()


class TestDocumentsAreCurrent:
    @pytest.mark.parametrize("relative", DOCUMENTS)
    def test_committed_file_matches_the_generator(
        self, rendered: dict[str, str], relative: str
    ) -> None:
        path = REPO_ROOT / relative
        assert path.is_file(), f"{relative} is missing"
        assert path.read_text(encoding="utf-8") == rendered[relative], (
            f"{relative} is stale — regenerate it with `make docs`"
        )

    @pytest.mark.parametrize("relative", DOCUMENTS)
    def test_the_generator_version_is_stamped(
        self, rendered: dict[str, str], relative: str
    ) -> None:
        """The stamp is what tells a reader which dataset the document describes.
        Both files carried `0.1.5` while the generator was at `0.1.6`."""
        assert f"`{GENERATOR_VERSION}`" in rendered[relative]

    @pytest.mark.parametrize("relative", DOCUMENTS)
    def test_the_file_is_marked_generated(
        self, rendered: dict[str, str], relative: str
    ) -> None:
        """So the next person edits the generator rather than the output."""
        assert "GENERATED by `make docs`" in rendered[relative]

    @pytest.mark.parametrize("relative", DOCUMENTS)
    def test_line_endings_are_lf(self, relative: str) -> None:
        """A CRLF here would fail the comparison above for a reason unrelated to
        the dataset (FR-012a)."""
        assert b"\r\n" not in (REPO_ROOT / relative).read_bytes()


class TestPersonaTableIsAccurate:
    def test_every_persona_appears(self, rendered: dict[str, str]) -> None:
        from eaios_seed.generators.organization import PERSONA_PLACEMENT

        content = rendered["docs/personas.md"]
        for key in PERSONA_PLACEMENT:
            assert f"`{key}`" in content, f"{key} is absent from the persona reference"

    def test_the_documented_profile_is_named(self, rendered: dict[str, str]) -> None:
        """Persona *names* differ between the full and smoke profiles, because the
        user population they are drawn from differs. Without the profile stated,
        a reader comparing this table against a smoke environment concludes it is
        wrong — which is exactly what happened."""
        assert "profile `full`" in rendered["docs/personas.md"]

    def test_names_come_from_the_dataset_not_the_prose(
        self, rendered: dict[str, str]
    ) -> None:
        """Guards against the table being hand-maintained again: every name in it
        must be a real generated user."""
        from eaios_seed.config import SeedConfig
        from eaios_seed.pipeline import build_complete_dataset

        dataset, _ctx = build_complete_dataset(SeedConfig.build(profile="full"))
        names = {user["full_name"] for user in dataset.rows["users"]}
        personas = [user for user in dataset.rows["users"] if user.get("persona_key")]
        assert personas, "no personas in the dataset"
        for user in personas:
            assert user["full_name"] in names
            assert f"| {user['full_name']} |" in rendered["docs/personas.md"]


class TestDatasetDocumentIsAccurate:
    def test_the_fingerprint_is_the_current_one(self, rendered: dict[str, str]) -> None:
        from eaios_seed.config import SeedConfig
        from eaios_seed.manifest import compute_digests
        from eaios_seed.pipeline import build_complete_dataset

        dataset, ctx = build_complete_dataset(SeedConfig.build(profile="full"))
        _families, _files, root = compute_digests(dataset, ctx.company_ids)
        assert f"`{root}`" in rendered["docs/dataset.md"], (
            "the documented fingerprint is not the one the generator produces"
        )

    def test_realized_counts_are_present_and_plural(
        self, rendered: dict[str, str]
    ) -> None:
        content = rendered["docs/dataset.md"]
        assert "## Realized counts" in content
        assert content.count("| `niletech.") > 20, "the counts table looks truncated"
        assert content.count("| `delta-retail.") > 20


class TestTheCheckCanFail:
    def test_a_modified_document_is_detected(self, rendered: dict[str, str]) -> None:
        """A freshness check that cannot notice a change is decoration."""
        tampered = rendered["docs/personas.md"] + "\nstray line\n"
        assert tampered != rendered["docs/personas.md"]

    def test_rendering_is_stable_between_calls(self) -> None:
        """Otherwise the check would fail at random and get disabled."""
        assert render_all() == render_all()
